# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0b195970b6dc96fd2242045255e443930e82177713fcc2ca63c9ac7b4a1d703ebe65aa5e8933d7a11c2c61de6127e9c5a1a6958f0d6a51fca1ef89a00c3e562

test:
  secret_key_base: 48df7f34eda8f35fed8892b5ff1d94bac4dd718c3413954047caf61dd45e6c67080d6f5a04928afd723123c97b4c2b1448e6b59e70fbb9fedb7bd157edc53f23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
